kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: test
  namespace: nginx-ingress
spec:
  to:
    kind: Service
    name: nginxingress-sample-nginx-ingress
    weight: 100
  port:
    targetPort: http80
  wildcardPolicy: None
